name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Build Docker Image
        run: |
          docker build -t my-spring-boot-app .
          docker images

      - name: Run Docker Container
        run: docker run -d --name my-app-container -p 8080:8080 my-spring-boot-app
